<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc0f91dcbfbd782d6faae455cd09a4431
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'ClickHouseDB\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ClickHouseDB\\' => 
        array (
            0 => __DIR__ . '/..' . '/smi2/phpclickhouse/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc0f91dcbfbd782d6faae455cd09a4431::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc0f91dcbfbd782d6faae455cd09a4431::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc0f91dcbfbd782d6faae455cd09a4431::$classMap;

        }, null, ClassLoader::class);
    }
}
